version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: newsportal-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: NewsPortalCMS
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsportal-api
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__DefaultConnection: Host=host.docker.internal;Port=5433;Database=NewsPortalCMS;Username=postgres;Password=randompassword
    depends_on:
      - postgres

volumes:
  postgres_data:
